services:
  php:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-php/giphy-challenge:1.0
    volumes:
      - ./project-folder:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./project-folder/:/var/www/html:ro
    depends_on:
      - php
    networks:
      - laravel-net
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-net
  
  mysql-test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-test
      MYSQL_USER: laravel-test
      MYSQL_PASSWORD: laravel-test
    ports:
      - "3308:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql
    networks:
      - laravel-net

networks:
  laravel-net:
    driver: bridge

volumes:
  mysql-data:
  mysql-test-data: